# .github/workflows/update-conda-locks.yml
on:
  push:
    paths:
      - 'pixi.lock'
      - '.github/workflows/update-conda-locks.yml'

jobs:
  update-conda-locks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install pixi-to-conda-lock
      - run: |
          pixi-to-conda-lock --environment cellpose3 pixi.lock
          pixi-to-conda-lock --environment cellpose4 pixi.lock
          pixi-to-conda-lock --environment micro-sam pixi.lock
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: update conda-lock files"
          file_pattern: "*.conda-lock.yml"
